name: Check PR, merge if ok

on: issue_comment

jobs:
  pr_check_owner_comment:
    name: PR comment
    if: |
      github.event.issue.pull_request
      && github.event.comment.body == '/check'
      && github.event.comment.author_association == 'OWNER'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: refs/pull/${{ github.event.issue.number }}/merge

      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: check
        run: nix build .#pushall

      - name: merge
        run: gh pr merge ${{ github.event.issue.number }} --merge --admin
        env:
          GH_TOKEN: ${{ secrets.MERGE_TOKEN }}

      - name: report issues
        if: failure()
        run: gh pr comment ${{ github.event.issue.number }} --body "Check failed, see [action run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) for details"
        env:
          GH_TOKEN: ${{ github.token }}